// Pre-seeded comprehensive data for PetCare+
export const seedUsers = [
  {
    _id: 'user_darshan',
    name: 'Darshan',
    email: 'darshandarji8066@gmail.com',
    password: '$2a$10$YourHashedPasswordHereOrDemoFallback1234567890',
    role: 'user',
    phone: '+1 (555) 382-9011',
    address: {
      street: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'OR',
      zipCode: '97477',
      country: 'USA'
    },
    emergencyContact: {
      name: 'Sarah Darshan',
      phone: '+1 (555) 382-9012',
      relationship: 'Spouse'
    },
    subscriptionPlan: 'premium',
    subscriptionValidUntil: '2027-01-01T00:00:00.000Z',
    emailVerified: true
  },
  {
    _id: 'user_admin',
    name: 'Administrator',
    email: 'admin@petcareplus.com',
    password: '$2a$10$YourHashedPasswordHereOrDemoFallback1234567890',
    role: 'admin',
    phone: '+1 (555) 000-1122',
    subscriptionPlan: 'premium',
    emailVerified: true
  }
];

export const seedPets = [
  {
    _id: 'pet_milo',
    ownerId: 'user_darshan',
    name: 'Milo',
    species: 'Dog',
    breed: 'Golden Retriever',
    gender: 'Male',
    dateOfBirth: '2023-06-14',
    weight: 28,
    color: 'Golden',
    avatar: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&auto=format&fit=crop&q=80',
    microchipped: true,
    microchipNumber: '985141002348123',
    allergies: ['Chicken', 'Tree pollen', 'Penicillin'],
    medicalConditions: ['Seasonal Allergies', 'Mild hip sensitivity'],
    notes: 'Friendly, high energy. Enjoys tennis balls and swimming. Sensitive to poultry treats.',
    primaryVet: {
      name: 'Dr. Elena Alvarez',
      clinic: 'Meadowbrook Animal Clinic',
      phone: '+1 (555) 234-5678'
    },
    insurance: {
      provider: 'Healthy Paws Pet Insurance',
      policyNumber: 'HP-90218-GOLD'
    }
  },
  {
    _id: 'pet_luna',
    ownerId: 'user_darshan',
    name: 'Luna',
    species: 'Cat',
    breed: 'Ragdoll',
    gender: 'Female',
    dateOfBirth: '2024-03-20',
    weight: 4.2,
    color: 'Seal Point',
    avatar: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&auto=format&fit=crop&q=80',
    microchipped: true,
    microchipNumber: '985141002348999',
    allergies: ['Dust mites'],
    medicalConditions: [],
    notes: 'Very calm indoor cat. Prefers wet salmon food.',
    primaryVet: {
      name: 'Dr. Elena Alvarez',
      clinic: 'Meadowbrook Animal Clinic',
      phone: '+1 (555) 234-5678'
    }
  }
];

export const seedVets = [
  {
    _id: 'vet_1',
    name: 'Dr. Elena Alvarez, DVM',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    title: 'Chief Medical Director & Senior Small Animal Clinician',
    specialty: 'Internal Medicine & Preventive Health',
    qualification: 'DVM (Cornell), Board Certified Veterinary Internist (DACVIM)',
    experienceYears: 14,
    clinicName: 'Meadowbrook Animal Hospital',
    clinicAddress: '420 West Green Blvd, Springfield, OR',
    consultationFee: 65,
    videoConsultationFee: 40,
    rating: 4.96,
    reviewCount: 312,
    about: 'Dr. Alvarez brings 14 years of clinical experience specializing in cardiology, routine screenings, and geriatric pet care.',
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    availableSlots: ['09:00 AM', '10:30 AM', '02:00 PM', '04:00 PM'],
    phone: '+1 (555) 234-5678',
    isAvailableToday: true
  },
  {
    _id: 'vet_2',
    name: 'Dr. Marcus Vance, DVM',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    title: 'Veterinary Surgeon & Orthopedic Consultant',
    specialty: 'Soft Tissue & Orthopedic Surgery',
    qualification: 'DVM (UC Davis), Small Animal Surgery Resident Alumni',
    experienceYears: 11,
    clinicName: 'Valley Emergency & Specialty Pet Center',
    clinicAddress: '1108 South Riverway, Springfield, OR',
    consultationFee: 85,
    videoConsultationFee: 50,
    rating: 4.91,
    reviewCount: 198,
    about: 'Specializes in minimally invasive orthopedic and soft-tissue surgical interventions with gentle bedside manner.',
    availableDays: ['Tue', 'Wed', 'Thu', 'Fri'],
    availableSlots: ['11:00 AM', '01:30 PM', '03:30 PM'],
    phone: '+1 (555) 345-6789',
    isAvailableToday: true
  },
  {
    _id: 'vet_3',
    name: 'Dr. Priya Nair, BVSc',
    photo: 'https://images.unsplash.com/photo-1594824813598-c178229bbfd2?w=400&auto=format&fit=crop&q=80',
    title: 'Holistic & Integrative Veterinary Practitioner',
    specialty: 'Dermatology & Nutrition Therapy',
    qualification: 'BVSc & AH, Certified Veterinary Acupuncturist (CVA)',
    experienceYears: 8,
    clinicName: 'Harmony Pet Wellness Studio',
    clinicAddress: '78 Pine Grove Way, Springfield, OR',
    consultationFee: 60,
    videoConsultationFee: 35,
    rating: 4.88,
    reviewCount: 145,
    about: 'Focused on chronic skin conditions, pet allergy testing, and customized organic nutrition planning.',
    availableDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    availableSlots: ['10:00 AM', '12:00 PM', '03:00 PM', '05:00 PM'],
    phone: '+1 (555) 456-7890',
    isAvailableToday: false
  }
];

export const seedGroomers = [
  {
    _id: 'groomer_1',
    name: 'Chloe Tremblay',
    businessName: 'Velvet Paws Luxury Pet Spa',
    photo: 'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=400&auto=format&fit=crop&q=80',
    rating: 4.95,
    reviewCount: 184,
    location: '128 Willow Creek Way, Springfield',
    services: [
      { id: 'g1', name: 'Full Luxury Spa Grooming', duration: '90 mins', price: 75, description: 'Hydrating organic bath, gentle blowout, breed haircut, nail grinding, and ear cleansing.' },
      { id: 'g2', name: 'De-Shedding Treatment', duration: '60 mins', price: 55, description: 'Deep coat undercoat rake, high-velocity blowout, and smoothing shine spray.' },
      { id: 'g3', name: 'Nail Trim & Paw Balm', duration: '20 mins', price: 20, description: 'Precision nail clip, Dremel smoothing, and organic beeswax paw pad moisture massage.' }
    ],
    providesHomeGrooming: true,
    providesSalonGrooming: true,
    about: 'Certified Master Pet Stylist specializing in calm, low-stress handling for anxious and senior pets.'
  },
  {
    _id: 'groomer_2',
    name: 'Oliver Vance',
    businessName: 'The Dapper Dog Mobile Grooming',
    photo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80',
    rating: 4.89,
    reviewCount: 112,
    location: 'Mobile Service — We come directly to your driveway!',
    services: [
      { id: 'g4', name: 'Mobile Van Full Groom', duration: '75 mins', price: 90, description: 'Self-contained luxury van grooming parked outside your doorstep.' },
      { id: 'g5', name: 'Teeth Brushing & Breath Freshener', duration: '15 mins', price: 15, description: 'Enzymatic plaque gel brush and natural herbal breath mist.' }
    ],
    providesHomeGrooming: true,
    providesSalonGrooming: false,
    about: 'Fully equipped luxury Mercedes mobile grooming van with warm water and organic shampoos.'
  }
];

export const seedSitters = [
  {
    _id: 'sitter_1',
    name: 'Samantha Ross',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    rating: 4.98,
    reviewCount: 167,
    location: 'Springfield North & Downtown',
    verified: true,
    experienceYears: 7,
    services: [
      { name: 'Overnight House Boarding', rate: 55, unit: 'per night' },
      { name: 'Day Pet Sitting & Playdate', rate: 35, unit: 'per day' },
      { name: 'Solo 45-min Nature Walk', rate: 25, unit: 'per walk' }
    ],
    about: 'Certified pet first-aid responder with a fenced acre backyard. Sends hourly photos & video updates!',
    availability: 'Available Daily'
  },
  {
    _id: 'sitter_2',
    name: 'Lucas Campbell',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    rating: 4.92,
    reviewCount: 89,
    location: 'Springfield South Hills',
    verified: true,
    experienceYears: 4,
    services: [
      { name: 'Quick 30-min Dog Walk', rate: 20, unit: 'per walk' },
      { name: 'Cat & Small Pet Drop-In Visit', rate: 22, unit: 'per visit' },
      { name: 'Trail Adventure Hike (2 hrs)', rate: 45, unit: 'per hike' }
    ],
    about: 'Energetic outdoor enthusiast who loves taking dogs on wooded trail hikes and ensuring cats are cuddled.',
    availability: 'Mornings & Evenings'
  }
];

export const seedProducts = [
  // Dog Accessories & Products
  {
    _id: 'prod_acc_1',
    title: 'Ergonomic No-Pull Reflective Dog Harness',
    brand: 'PetSafe Comfort',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 26.99,
    originalPrice: 34.99,
    rating: 4.9,
    reviewCount: 1420,
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=500&auto=format&fit=crop&q=80',
    description: 'Padded breathable mesh with front/back dual leash attachment rings and high-visibility 3M reflective trim.',
    inStock: true,
    stockCount: 85,
    isBestSeller: true,
    isFeatured: true,
    tags: ['Accessories', 'Harness', 'Reflective', 'No-Pull']
  },
  {
    _id: 'prod_acc_2',
    title: 'Adjustable Waterproof Silicone LED Dog Safety Collar',
    brand: 'LumiGlow Pets',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 16.50,
    originalPrice: 21.99,
    rating: 4.8,
    reviewCount: 680,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=500&auto=format&fit=crop&q=80',
    description: 'USB rechargeable glowing collar with 3 illumination modes visible up to 500 meters during night walks.',
    inStock: true,
    stockCount: 110,
    isBestSeller: true,
    tags: ['Accessories', 'Night Safety', 'LED Collar', 'Rechargeable']
  },
  {
    _id: 'prod_acc_3',
    title: 'Heavy-Duty Shock-Absorbing Bungee Dog Leash (6ft)',
    brand: 'TrekHound',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 22.95,
    originalPrice: 28.00,
    rating: 4.88,
    reviewCount: 920,
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=500&auto=format&fit=crop&q=80',
    description: 'Dual padded traffic control handles and aircraft-grade aluminum locking carabiner for dogs.',
    inStock: true,
    stockCount: 64,
    tags: ['Accessories', 'Leash', 'Walking', 'Bungee']
  },
  {
    _id: 'prod_acc_4',
    title: 'Double Stainless Steel Elevated Dog Bowls with Non-Spill Mat',
    brand: 'ZenFeeder',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 29.99,
    originalPrice: 36.99,
    rating: 4.92,
    reviewCount: 1150,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&auto=format&fit=crop&q=80',
    description: 'Ergonomic raised feeding stand promoting comfortable canine swallowing and posture.',
    inStock: true,
    stockCount: 48,
    isFeatured: true,
    tags: ['Accessories', 'Bowls', 'Feeding', 'Stainless Steel']
  },
  {
    _id: 'prod_acc_6',
    title: 'Orthopedic Calming Memory Foam Dog Bed with Washable Cover',
    brand: 'SleepPaws Luxury',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 54.99,
    originalPrice: 69.99,
    rating: 4.96,
    reviewCount: 2200,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=500&auto=format&fit=crop&q=80',
    description: 'Therapeutic high-density medical grade memory foam relieving joint pressure and hip dysplasia in dogs.',
    inStock: true,
    stockCount: 38,
    isFeatured: true,
    tags: ['Accessories', 'Bedding', 'Orthopedic', 'Memory Foam']
  },
  {
    _id: 'prod_acc_8',
    title: 'Airline Approved Soft-Sided Dog Travel Carrier (Small & Medium Dogs)',
    brand: 'VoyagerPet',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 49.99,
    originalPrice: 59.99,
    rating: 4.91,
    reviewCount: 760,
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&auto=format&fit=crop&q=80',
    description: 'Meets TSA flight dimensions with reinforced frame, cozy plush bedding, and seatbelt clips.',
    inStock: true,
    stockCount: 30,
    tags: ['Accessories', 'Carrier', 'Travel', 'Airline Approved']
  },
  {
    _id: 'prod_acc_9',
    title: 'Professional Self-Cleaning Deshedding Undercoat Dog Rake',
    brand: 'DuoGroom Pro',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 19.99,
    originalPrice: 25.00,
    rating: 4.87,
    reviewCount: 1540,
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=500&auto=format&fit=crop&q=80',
    description: 'Dual-sided stainless steel rounded teeth removing thick dog undercoat without scratching skin.',
    inStock: true,
    stockCount: 95,
    tags: ['Accessories', 'Grooming', 'Brush', 'Deshedding']
  },
  {
    _id: 'prod_acc_10',
    title: 'Waterproof All-Weather Reflective Dog Raincoat with Hood',
    brand: 'StormPaws',
    category: 'Pet Accessories',
    targetPet: 'Dog',
    price: 24.50,
    originalPrice: 32.00,
    rating: 4.75,
    reviewCount: 430,
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=500&auto=format&fit=crop&q=80',
    description: 'High visibility yellow dog raincoat keeping your pup dry and clean on rainy walks.',
    inStock: true,
    stockCount: 42,
    tags: ['Accessories', 'Apparel', 'Raincoat', 'Waterproof']
  },
  {
    _id: 'prod_1',
    title: 'Purina Pro Plan Adult Sensitive Skin & Stomach Formula (Salmon & Rice)',
    brand: 'Purina Pro Plan',
    category: 'Dog Food',
    targetPet: 'Dog',
    price: 68.99,
    originalPrice: 79.99,
    rating: 4.9,
    reviewCount: 2480,
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=500&auto=format&fit=crop&q=80',
    description: 'Real salmon #1 ingredient with rice for easy digestion. Fortified with guaranteed live probiotics.',
    inStock: true,
    stockCount: 45,
    isBestSeller: true,
    isFeatured: true,
    tags: ['Digestive Health', 'Sensitive Skin', 'Salmon', 'Probiotics']
  },
  {
    _id: 'prod_3',
    title: 'Zesty Paws Glucosamine Joint & Hip Soft Chews for Dogs (90 Count)',
    brand: 'Zesty Paws',
    category: 'Vitamins & Supplements',
    targetPet: 'Dog',
    price: 32.97,
    originalPrice: 36.99,
    rating: 4.9,
    reviewCount: 1650,
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=500&auto=format&fit=crop&q=80',
    description: 'Advanced canine joint support chews formulated with OptiMSM, Chondroitin, and Glucosamine.',
    inStock: true,
    stockCount: 80,
    isBestSeller: true,
    tags: ['Joint Support', 'Glucosamine', 'Mobility', 'Senior Care']
  },
  {
    _id: 'prod_4',
    title: 'KONG Classic Interactive Ultra-Durable Rubber Dog Toy',
    brand: 'KONG',
    category: 'Toys & Enrichment',
    targetPet: 'Dog',
    price: 14.99,
    originalPrice: 17.99,
    rating: 4.95,
    reviewCount: 4200,
    image: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=500&auto=format&fit=crop&q=80',
    description: 'The gold standard of dog toys for over 40 years. Mentally stimulating and stuffable with treats.',
    inStock: true,
    stockCount: 120,
    isFeatured: true,
    tags: ['Durable', 'Mental Enrichment', 'Chew Toy']
  },
  {
    _id: 'prod_5',
    title: 'Frontline Plus Flea & Tick Prevention Treatment for Dogs (3 Doses)',
    brand: 'Boehringer Ingelheim',
    category: 'Pharmacy & Care',
    targetPet: 'Dog',
    price: 48.99,
    originalPrice: 54.99,
    rating: 4.85,
    reviewCount: 1190,
    image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=500&auto=format&fit=crop&q=80',
    description: 'Fast-acting, waterproof topical canine treatment that kills adult fleas, flea eggs, larvae, and ticks.',
    inStock: true,
    stockCount: 35,
    tags: ['Flea & Tick', 'Prescription Care', 'Waterproof']
  },

  // Cat Accessories & Products (Pure Cat Photos & Products)
  {
    _id: 'prod_acc_5',
    title: 'Ultra-Quiet 2.5L Quadruple-Filter Cat Water Drinking Fountain',
    brand: 'AquaPurr Pure',
    category: 'Pet Accessories',
    targetPet: 'Cat',
    price: 38.50,
    originalPrice: 48.00,
    rating: 4.85,
    reviewCount: 1310,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=500&auto=format&fit=crop&q=80',
    description: 'Whisper-quiet circulating fresh filtered water fountain enticing cats to stay properly hydrated.',
    inStock: true,
    stockCount: 52,
    isBestSeller: true,
    tags: ['Accessories', 'Hydration', 'Water Fountain', 'Filtration']
  },
  {
    _id: 'prod_acc_7',
    title: 'Multi-Level Sisal Cat Scratching Post Tree with Plush Hammock',
    brand: 'PawHaven',
    category: 'Pet Accessories',
    targetPet: 'Cat',
    price: 64.00,
    originalPrice: 79.99,
    rating: 4.79,
    reviewCount: 840,
    image: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=500&auto=format&fit=crop&q=80',
    description: 'Sturdy 42-inch climbing cat tower with natural Brazilian sisal posts, pom-pom, and resting condo.',
    inStock: true,
    stockCount: 26,
    tags: ['Accessories', 'Cat Furniture', 'Scratcher', 'Tower']
  },
  {
    _id: 'prod_acc_11',
    title: 'Breathable Capsule Bubble Window Cat Carrier Backpack',
    brand: 'FelineFlyer',
    category: 'Pet Accessories',
    targetPet: 'Cat',
    price: 42.00,
    originalPrice: 52.00,
    rating: 4.89,
    reviewCount: 910,
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=500&auto=format&fit=crop&q=80',
    description: 'Clear panorama window bubble backpack with 9 large ventilation holes for scenic outdoor cat trips.',
    inStock: true,
    stockCount: 34,
    tags: ['Accessories', 'Carrier', 'Travel', 'Cat Backpack']
  },
  {
    _id: 'prod_acc_12',
    title: 'Marshmallow Plush Self-Warming Calming Donut Cat Bed',
    brand: 'CloudKitten',
    category: 'Pet Accessories',
    targetPet: 'Cat',
    price: 31.99,
    originalPrice: 39.99,
    rating: 4.93,
    reviewCount: 1140,
    image: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=500&auto=format&fit=crop&q=80',
    description: 'Shag faux-fur donut lounger providing neck and head support for deep, calming cat sleep.',
    inStock: true,
    stockCount: 45,
    isFeatured: true,
    tags: ['Accessories', 'Bedding', 'Calming', 'Cat Bed']
  },
  {
    _id: 'prod_2',
    title: 'Wellness CORE Grain-Free Turkey & Duck Pate Wet Cat Food (12-pack)',
    brand: 'Wellness',
    category: 'Cat Food',
    targetPet: 'Cat',
    price: 34.50,
    originalPrice: 39.99,
    rating: 4.88,
    reviewCount: 840,
    image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=500&auto=format&fit=crop&q=80',
    description: 'High-protein, grain-free premium wet cat food crafted with tender cuts of turkey and duck.',
    inStock: true,
    stockCount: 60,
    isBestSeller: true,
    tags: ['Grain Free', 'High Protein', 'Wet Cat Food']
  },
  {
    _id: 'prod_cat_1',
    title: 'Royal Canin Feline Health Nutrition Indoor Adult Dry Cat Food',
    brand: 'Royal Canin',
    category: 'Cat Food',
    targetPet: 'Cat',
    price: 49.99,
    originalPrice: 57.99,
    rating: 4.92,
    reviewCount: 1820,
    image: 'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=500&auto=format&fit=crop&q=80',
    description: 'Formulated with precise calories and fiber to reduce hairballs and maintain a healthy weight in indoor cats.',
    inStock: true,
    stockCount: 50,
    isFeatured: true,
    tags: ['Indoor Cat', 'Hairball Control', 'Dry Food']
  },
  {
    _id: 'prod_cat_2',
    title: 'Feline Greenies Natural Dental Treats (Catnip Flavor)',
    brand: 'Greenies',
    category: 'Vitamins & Supplements',
    targetPet: 'Cat',
    price: 13.49,
    originalPrice: 16.99,
    rating: 4.94,
    reviewCount: 2300,
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=500&auto=format&fit=crop&q=80',
    description: 'Crunchy cat treats designed to clean teeth, reduce tartar buildup, and freshen cat breath.',
    inStock: true,
    stockCount: 90,
    isBestSeller: true,
    tags: ['Dental Care', 'Cat Treats', 'Catnip']
  },
  {
    _id: 'prod_cat_3',
    title: 'Interactive 3-in-1 Feather Wand & Red Laser Cat Toy',
    brand: 'KittyFun',
    category: 'Toys & Enrichment',
    targetPet: 'Cat',
    price: 15.99,
    originalPrice: 19.99,
    rating: 4.86,
    reviewCount: 770,
    image: 'https://images.unsplash.com/photo-1513360309081-9844bb688e29?w=500&auto=format&fit=crop&q=80',
    description: 'Stimulates natural hunting instincts with telescopic carbon-fiber wand and USB rechargeable laser pointer.',
    inStock: true,
    stockCount: 65,
    tags: ['Cat Toys', 'Feather Wand', 'Laser', 'Enrichment']
  }
];

// 20 Full Pet Profiles for Adoption & Marketplace
export const seedPetListings = [
  {
    _id: 'listing_1',
    title: 'Golden Retriever Puppies — Champion Pedigree',
    species: 'Dog',
    breed: 'Golden Retriever',
    age: '8 Weeks',
    gender: 'Male',
    price: 650,
    isForAdoption: false,
    location: 'Springfield, OR',
    description: 'Healthy, socialized Golden Retriever puppy raised with children. First vaccination rounds, deworming, and vet health passport included.',
    photos: [
      'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591160690555-5debfba289f0?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_darshan',
    sellerName: 'Darshan (Verified Breeder)',
    sellerPhone: '+1 (555) 382-9011',
    sellerEmail: 'darshandarji8066@gmail.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_2',
    title: 'Sweet Purebred Ragdoll Kitten with Blue Eyes',
    species: 'Cat',
    breed: 'Ragdoll',
    age: '10 Weeks',
    gender: 'Female',
    price: 450,
    isForAdoption: false,
    location: 'Eugene, OR',
    description: 'Fluffy seal-point Ragdoll with silky soft coat and tranquil personality. Litter-box trained, microchipped, and loves lap snuggles.',
    photos: [
      'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_2',
    sellerName: 'Emily Clark',
    sellerPhone: '+1 (555) 492-1100',
    sellerEmail: 'emily.ragdolls@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_3',
    title: 'Buster — Gentle Rescue Beagle Mix (Free Adoption)',
    species: 'Dog',
    breed: 'Beagle Mix',
    age: '2 Years',
    gender: 'Male',
    price: 0,
    isForAdoption: true,
    location: 'Springfield, OR',
    description: 'Buster is a calm, leash-trained rescue searching for his forever couch. Neutered, microchipped, and great with children and cats.',
    photos: [
      'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_shelter_1',
    sellerName: 'Cascade Animal Rescue Shelter',
    sellerPhone: '+1 (555) 880-9911',
    sellerEmail: 'adoptions@cascaderescue.org',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_4',
    title: 'Playful French Bulldog Puppy (Cream & White)',
    species: 'Dog',
    breed: 'French Bulldog',
    age: '12 Weeks',
    gender: 'Male',
    price: 850,
    isForAdoption: false,
    location: 'Portland, OR',
    description: 'Compact, muscular little boy with great breathing conformation, vet cleared, microchipped, and very affectionate.',
    photos: [
      'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_3',
    sellerName: 'Marcus Bennett',
    sellerPhone: '+1 (555) 301-4499',
    sellerEmail: 'marcus.frenchies@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_5',
    title: 'Luna & Cleo — Bonded Pair of British Shorthairs',
    species: 'Cat',
    breed: 'British Shorthair',
    age: '1 Year',
    gender: 'Female',
    price: 300,
    isForAdoption: false,
    location: 'Salem, OR',
    description: 'Quiet, aristocratic silver tabby sisters who love sunny windowsills and laser pointers. Up to date on all feline core vaccines.',
    photos: [
      'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_4',
    sellerName: 'Chloe Henderson',
    sellerPhone: '+1 (555) 722-6611',
    sellerEmail: 'chloe.cats@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_6',
    title: 'Zeus — Athletic German Shepherd Working Line',
    species: 'Dog',
    breed: 'German Shepherd',
    age: '10 Months',
    gender: 'Male',
    price: 500,
    isForAdoption: false,
    location: 'Bend, OR',
    description: 'Intelligent, loyal German Shepherd with basic obedience and leash training completed. Needs an active outdoorsy family.',
    photos: [
      'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_5',
    sellerName: 'David Vance',
    sellerPhone: '+1 (555) 619-3388',
    sellerEmail: 'david.gsd@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_7',
    title: 'Bella — Affectionate Calico Rescue Cat (Adoption)',
    species: 'Cat',
    breed: 'Domestic Shorthair / Calico',
    age: '3 Years',
    gender: 'Female',
    price: 0,
    isForAdoption: true,
    location: 'Eugene, OR',
    description: 'Spayed, friendly, litter trained, and loves head scratches. Rescued from foster care and eager for a cozy forever home.',
    photos: [
      'https://images.unsplash.com/photo-1548247416-ec66f4900b2e?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_shelter_1',
    sellerName: 'Cascade Animal Rescue Shelter',
    sellerPhone: '+1 (555) 880-9911',
    sellerEmail: 'adoptions@cascaderescue.org',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_8',
    title: 'Charlie — Hypoallergenic Mini Labradoodle Puppy',
    species: 'Dog',
    breed: 'Labradoodle',
    age: '9 Weeks',
    gender: 'Male',
    price: 700,
    isForAdoption: false,
    location: 'Springfield, OR',
    description: 'Non-shedding fleece coat, low-allergen pup. Raised indoors with puppy culture training. Comes with first puppy care kit.',
    photos: [
      'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_6',
    sellerName: 'Hannah Wright',
    sellerPhone: '+1 (555) 942-8822',
    sellerEmail: 'hannah.doodles@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_9',
    title: 'Snowball — Pure White Holland Lop Bunny',
    species: 'Rabbit',
    breed: 'Holland Lop',
    age: '4 Months',
    gender: 'Male',
    price: 60,
    isForAdoption: false,
    location: 'Corvallis, OR',
    description: 'Gentle, hand-tamed lop-eared bunny who loves Timothy hay and carrot tops. Comes with transition feed and hay rack.',
    photos: [
      'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_7',
    sellerName: 'Rachel Miller',
    sellerPhone: '+1 (555) 431-7711',
    sellerEmail: 'rachel.bunnies@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_10',
    title: 'Sunny — Hand-Fed Cockatiel Whistling Companion',
    species: 'Bird',
    breed: 'Cockatiel',
    age: '6 Months',
    gender: 'Male',
    price: 120,
    isForAdoption: false,
    location: 'Portland, OR',
    description: 'Extremely sweet, step-up trained Cockatiel who whistles tunes and enjoys sitting on shoulders while you work.',
    photos: [
      'https://images.unsplash.com/photo-1522858547550-340574cd2f33?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: false,
    healthCertificate: true,
    sellerId: 'user_seller_8',
    sellerName: 'Jonathan Reed',
    sellerPhone: '+1 (555) 882-1400',
    sellerEmail: 'jon.aviary@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_11',
    title: 'Rocky — High-Energy Siberian Husky with Ice-Blue Eyes',
    species: 'Dog',
    breed: 'Siberian Husky',
    age: '1.5 Years',
    gender: 'Male',
    price: 350,
    isForAdoption: false,
    location: 'Medford, OR',
    description: 'Talkative, stunning husky who loves jogging, hiking, and snow. Microchipped, neutered, and fully vaccinated.',
    photos: [
      'https://images.unsplash.com/photo-1538815087782-47b186736570?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_9',
    sellerName: 'Travis Logan',
    sellerPhone: '+1 (555) 777-3311',
    sellerEmail: 'travis.huskies@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_12',
    title: 'Thor — Magnificent Maine Coon Gentle Giant',
    species: 'Cat',
    breed: 'Maine Coon',
    age: '1 Year',
    gender: 'Male',
    price: 550,
    isForAdoption: false,
    location: 'Eugene, OR',
    description: 'Large, fluffy lynx-tipped ears, affectionate trilling meow, and dog-like friendly demeanor. Up to date on veterinary checks.',
    photos: [
      'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_10',
    sellerName: 'Natalie Brooks',
    sellerPhone: '+1 (555) 555-8922',
    sellerEmail: 'natalie.coons@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_13',
    title: 'Oreo — Miniature Black & White Dutch Rabbit',
    species: 'Rabbit',
    breed: 'Dutch Rabbit',
    age: '5 Months',
    gender: 'Female',
    price: 45,
    isForAdoption: false,
    location: 'Springfield, OR',
    description: 'Very gentle, calm disposition. Enjoys gentle petting and fresh greens. Perfect indoor companion pet.',
    photos: [
      'https://images.unsplash.com/photo-1591382696684-38c427c7547a?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_7',
    sellerName: 'Rachel Miller',
    sellerPhone: '+1 (555) 431-7711',
    sellerEmail: 'rachel.bunnies@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_14',
    title: 'Daisy — Corgi Puppy with Natural Bobtail',
    species: 'Dog',
    breed: 'Pembroke Welsh Corgi',
    age: '11 Weeks',
    gender: 'Female',
    price: 750,
    isForAdoption: false,
    location: 'Salem, OR',
    description: 'Charming, alert, and full of personality. Well socialized with children and other dogs. First vaccinations complete.',
    photos: [
      'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_11',
    sellerName: 'Brandon Lee',
    sellerPhone: '+1 (555) 229-8471',
    sellerEmail: 'brandon.corgis@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_15',
    title: 'Mocha — Chocolate Labrador Retriever (Adoption)',
    species: 'Dog',
    breed: 'Labrador Retriever',
    age: '3 Years',
    gender: 'Female',
    price: 0,
    isForAdoption: true,
    location: 'Springfield, OR',
    description: 'Rescued loving family dog. Loves swimming, retrieving tennis balls, and giving kisses. Great with other pets.',
    photos: [
      'https://images.unsplash.com/photo-1579202673506-ca3ce28943ef?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_shelter_1',
    sellerName: 'Cascade Animal Rescue Shelter',
    sellerPhone: '+1 (555) 880-9911',
    sellerEmail: 'adoptions@cascaderescue.org',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_16',
    title: 'Kiwi — Colorful English Budgerigar (Parakeet)',
    species: 'Bird',
    breed: 'Parakeet',
    age: '4 Months',
    gender: 'Male',
    price: 35,
    isForAdoption: false,
    location: 'Eugene, OR',
    description: 'Vibrant green and yellow budgie. Active chirper, healthy plumage, finger tame.',
    photos: [
      'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: false,
    dewormed: false,
    healthCertificate: true,
    sellerId: 'user_seller_8',
    sellerName: 'Jonathan Reed',
    sellerPhone: '+1 (555) 882-1400',
    sellerEmail: 'jon.aviary@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_17',
    title: 'Simba — Fold-Eared Scottish Fold Kitten',
    species: 'Cat',
    breed: 'Scottish Fold',
    age: '12 Weeks',
    gender: 'Male',
    price: 500,
    isForAdoption: false,
    location: 'Portland, OR',
    description: 'Round owl-like eyes, folded ears, and sweet temperament. Microchipped and vet checked with pedigree.',
    photos: [
      'https://images.unsplash.com/photo-1561948955-570b270e7c36?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_12',
    sellerName: 'Victoria Price',
    sellerPhone: '+1 (555) 819-3300',
    sellerEmail: 'victoria.folds@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_18',
    title: 'Shadow — Sleek Bombay Mini-Panther Cat (Adoption)',
    species: 'Cat',
    breed: 'Bombay Cat',
    age: '2 Years',
    gender: 'Male',
    price: 0,
    isForAdoption: true,
    location: 'Springfield, OR',
    description: 'Glossy black coat with amber copper eyes. Affectionate cuddler who gets along nicely with dogs.',
    photos: [
      'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_shelter_1',
    sellerName: 'Cascade Animal Rescue Shelter',
    sellerPhone: '+1 (555) 880-9911',
    sellerEmail: 'adoptions@cascaderescue.org',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_19',
    title: 'Peanut — Fluffy Teddy Bear Syrian Hamster',
    species: 'Hamster',
    breed: 'Syrian Hamster',
    age: '3 Months',
    gender: 'Male',
    price: 25,
    isForAdoption: false,
    location: 'Eugene, OR',
    description: 'Friendly, easy to hold, nocturnal for evening cuddles. Includes starting running wheel and bedding bag.',
    photos: [
      'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: false,
    dewormed: false,
    healthCertificate: true,
    sellerId: 'user_seller_7',
    sellerName: 'Rachel Miller',
    sellerPhone: '+1 (555) 431-7711',
    sellerEmail: 'rachel.bunnies@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  },
  {
    _id: 'listing_20',
    title: 'Apollo — Purebred Red Standard Poodle',
    species: 'Dog',
    breed: 'Standard Poodle',
    age: '7 Months',
    gender: 'Male',
    price: 600,
    isForAdoption: false,
    location: 'Springfield, OR',
    description: 'Hypoallergenic curly red coat. Exceptional agility prospect, crate trained, knows sit, stay, down and fetch.',
    photos: [
      'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=600&auto=format&fit=crop&q=80'
    ],
    vaccinated: true,
    dewormed: true,
    healthCertificate: true,
    sellerId: 'user_seller_13',
    sellerName: 'Lucas Campbell',
    sellerPhone: '+1 (555) 500-6644',
    sellerEmail: 'lucas.poodles@example.com',
    status: 'available',
    createdAt: new Date().toISOString()
  }
];

export const seedEmergencyClinics = [
  {
    _id: 'emerg_1',
    name: 'Cascade 24/7 Emergency & Critical Pet Care',
    address: '1450 Gateway Blvd, Springfield, OR',
    phone: '+1 (555) 911-7387',
    hours: '24 Hours / 7 Days a week',
    openHours: 'Open 24/7 · 365 Days',
    isOpen24Hours: true,
    distance: '1.4 miles',
    emergencyFee: 95,
    facilities: ['Oxygen Therapy & Ventilator', 'Digital X-Ray & Ultrasound', 'Trauma Emergency Surgery', 'Onsite ICU & Blood Bank'],
    services: ['Oxygen Therapy & Ventilator', 'Digital X-Ray & Ultrasound', 'Trauma Emergency Surgery', 'Onsite ICU & Blood Bank']
  },
  {
    _id: 'emerg_2',
    name: 'Willamette Veterinary Emergency Hospital',
    address: '890 Franklin Blvd, Eugene, OR',
    phone: '+1 (555) 746-9900',
    hours: 'Open 24/7 (365 days)',
    openHours: 'Open 24/7 (365 days)',
    isOpen24Hours: true,
    distance: '4.2 miles',
    emergencyFee: 110,
    facilities: ['Advanced Surgical Suites', 'Neurology Evaluation', 'Toxicology & Antivenom Unit'],
    services: ['Advanced Surgical Suites', 'Neurology Evaluation', 'Toxicology & Antivenom Unit']
  }
];

export const seedVaccinations = [
  {
    _id: 'vac_1',
    petId: 'pet_milo',
    name: 'DHPP (Distemper, Parvo, Hepatitis, Parainfluenza)',
    givenDate: '2026-05-02',
    nextDueDate: '2027-05-02',
    veterinarian: 'Dr. Elena Alvarez',
    clinic: 'Meadowbrook Animal Clinic',
    batchNumber: 'V-88219-X',
    status: 'up_to_date',
    notes: 'Administered right shoulder subcutaneously. No adverse reaction.'
  },
  {
    _id: 'vac_2',
    petId: 'pet_milo',
    name: 'Rabies (3-Year Booster)',
    givenDate: '2025-06-15',
    nextDueDate: '2028-06-15',
    veterinarian: 'Dr. Elena Alvarez',
    clinic: 'Meadowbrook Animal Clinic',
    batchNumber: 'RAB-992-B',
    status: 'up_to_date',
    notes: 'Vaccination certificate issued.'
  }
];

export const seedMedicines = [
  {
    _id: 'med_1',
    petId: 'pet_milo',
    name: 'Apoquel (Oclacitinib) 16mg',
    dosage: '1 chewable tablet (16mg)',
    frequency: 'Once daily',
    timeOfDay: ['08:00 AM'],
    startDate: '2026-06-01',
    instructions: 'Administer with breakfast meal. Effective control of itching and allergic dermatitis.',
    status: 'active',
    history: [
      { date: '2026-06-01', time: '08:00 AM', status: 'taken' }
    ],
    notes: 'Prescribed by Dr. Alvarez for spring pollen allergies.'
  }
];
